version: "3.8"

services:
  phoenixd:
    image: nodana/phoenixd:0.5.0
    command: "--chain=testnet --http-password="
    volumes:
      - phoenixd-data:/root/.config/phoenix-daemon
    ports:
      - "9740:9740"
    networks:
      - l402-network

  phoenixd-client:
    image: nodana/phoenixd:0.5.0
    command: "--chain=testnet --http-password="
    volumes:
      - phoenixd-client-data:/root/.config/phoenix-daemon
    ports:
      - "4000:9740"
    networks:
      - l402-network

  server:
    build:
      context: .
      dockerfile: ./examples/server/Dockerfile
    environment:
      - PHOENIX_URL=http://phoenixd:9740
    ports:
      - "8080:8080"
    depends_on:
      - phoenixd
    networks:
      - l402-network

networks:
  l402-network:
    driver: bridge

volumes:
  phoenixd-data:
  phoenixd-client-data:
