name: Bug Report
description: File a bug report to help us improve.
title: "[Bug Report]: "
labels: ["bug"]
projects: ["Amper/1"]
assignees: []
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen.
      placeholder: Describe the issue in detail.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Software Version
      description: Specify the version of the software you are using.
      placeholder: e.g., 1.0.0
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser and Version
      description: Specify the browser and its version where the issue occurs.
      placeholder: e.g., Chrome 95.0.4638.69
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Error Messages
      description: Paste any relevant logs or error messages here.
      render: shell
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: You can drag and drop files or provide links to screenshots or other relevant files here.
      placeholder: Drag and drop files or paste links here.
